### ISSUE TITLE
Return a standard error response

### ISSUE THREAD

**Issue by kterusaki** [neonmaccca/mxtoolkit#1]
Hi @neonmaccca,

I'm using your node module to do mxlookups in my node.js app! Thanks for pioneering most of the work! One of the issues, I'm seeing is that there isn't an easy way to distinguish if the MxToolbox REST api returned any errors. Since both a success and error response returns a JSON string and there isn't an error property in the error response, I'm getting false negatives.

In your makeRequests function, what are your thoughts on generating an error response object like so:

```
function makeRequest(url,apiKey,callback) {
  console.log(url);
    var options = {
      headers:{
        'Authorization':apiKey,
        'Content-Type':'application/json'
      },
      uri: url,
      method: 'GET',
      json:true
   };
    var res = {};
    request(options, function (error, response, body) {
        if (!error && response.statusCode == 200) {
            res = body;
        }
        else {
           res.error_code = response.statusCode;
           res.body = body;                     
        }
        callback(JSON.stringify(res, null, 4));
    });
};
```

**Comment by neonmaccca** [comment]
Hi Thanks for the feedback.
Yes I am happy with that, let me do some tsting this week and I will let you know when I have this re issued to npm.

**Comment by neonmaccca** [comment]
I have merged your pull request and published to npm cheers.
