### ISSUE TITLE
`ptr` missing in apiRoutes

### ISSUE THREAD

**Issue by ljharb** [neonmaccca/mxtoolkit#4]
https://github.com/neonmaccca/mxtoolkit/blob/master/index.js#L56 refers to `apiRoutes.ptr`, but it's not in [apiRoutes](https://github.com/neonmaccca/mxtoolkit/blob/master/index.js#L3-L17).

**Comment by neonmaccca** [comment]
We didnt implement ptr. It can be added pretty easily though.

**Comment by ljharb** [comment]
The function exists, though - so either the bug is that the route is missing, or that the function exists, but either way it's broken.

**Comment by neonmaccca** [comment]
fix published to git and npm

**Comment by ljharb** [comment]
(Linking to 7aa3a804d5f4ac542a4a59e5df1cf73e1e9cf2ec)

Thanks!
